name: webots
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
      # Alternativa conda, as dependências estão definidas no pyproject.toml
      - "-e .[analysis]"
      - "pytest>=9.1.1"
